sensor: !include_dir_merge_list ../entities/sensor

homeassistant:
  customize:
    sensor.sensor_shelly_verbruik_kwh_huis:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
    sensor.sensor_shelly_verbruik_kwh_tuin:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
    sensor.sensor_shelly_verbruik_kwh_laadpaal:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
    sensor.sensor_shelly_injectie_kwh_tuin:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
    sensor.sensor_shelly_injectie_kwh_huis:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
    sensor.sensor_shelly_total_consumption:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh
    sensor.template_shelly_total_huis_injection:
      device_class: energy
      state_class: total
      unit_of_measurement: kWh