# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Hoefijzer
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels

frontend:
  themes: !include_dir_named themes

api:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

input_boolean:
  alexa_living_room_lights:
    name: Alexa living room lights
    icon: mdi:lightbulb-group

emulated_hue:
  listen_port: 80
  expose_by_default: false
  entities:
    input_boolean.alexa_living_room_lights:
      name: "Living room lights"
      hidden: false

timer:
  timer_airco_bureau_koelen:
    name: timer_airco_bureau_koelen
    duration: "00:30:00"
    icon: mdi:air-conditioner
  timer_airco_slaapkamer_koelen:
    name: timer_airco_slaapkamer_koelen
    duration: "00:30:00"
    icon: mdi:air-conditioner
  timer_airco_woonkamer_koelen:
    name: timer_airco_woonkamer_koelen
    duration: "00:30:00"
    icon: mdi:air-conditioner
  timer_jacuzzi:
    name: timer_jacuzzi
    duration: "00:15:00"
    icon: mdi:hot-tub
  timer_tuinlicht_jacuzzi:
    name: timer_tuinlicht_jacuzzi
    duration: "00:10:00"
    icon: mdi:outdoor-lamp
  timer_tuinhuis_ventilatie:
    name: timer_tuinhuis_ventilatie
    duration: "00:15:00"
    icon: mdi:fan
