alias: Laadpaal vermogen verlagen
id: laadpaal_vermogen_verlagen
description: Verlaag het laadvermorgen van de laadpaal vanaf 18u, of wanneer de Jacuzzi actief is
triggers:
  - at: "18:00"
    trigger: time
  - platform: state
    entity_id: binary_sensor.hoefijzer_spa_in_use
    to: "on"
action:
  - service: persistent_notification.create
    data:
      title: "Verlagen vermogen laadpaal Triggered"
      message: "Automation started and passed conditions"
  - service: number.set_value
    target:
      entity_id:
        - number.laadpaal_max_station_current
        - number.laadpaal_power_connector_external_max_current_socket_1
        - number.laadpaal_power_connector_max_current_socket_1
    data:
      value: 8
  - service: timer.start
    target:
      entity_id: timer.timer_jacuzzi
mode: restart

