alias: Laadpaal vermogen verhogen
id: laadpaal_vermogen_verhogen
description: Verhoog het laadvermorgen van de laadpaal vanaf 00:00, of wanneer de Jacuzzi niet actief is
triggers:
  - platform: time
    at: "00:00"
  - platform: state
    entity_id: binary_sensor.hoefijzer_spa_in_use
    to: "off"
  - platform: state
    entity_id: timer.timer_jacuzzi
    to: "idle"
condition:
  - condition: state
    entity_id: binary_sensor.hoefijzer_spa_in_use
    state: "off"
  - condition: state
    entity_id: timer.timer_jacuzzi 
    state: "idle"
  - condition: time
    before: "18:00"
action:
  - service: persistent_notification.create
    data:
      title: "Verhogen vermogen laadpaal Triggered"
      message: "Automation started and passed conditions"
  - service: number.set_value
    target:
      entity_id:
        - number.laadpaal_max_station_current
        - number.laadpaal_power_connector_external_max_current_socket_1
        - number.laadpaal_power_connector_max_current_socket_1
    data:
      value: 16
mode: restart