alias: Licht woonkamer uit
id: licht_woonkamer_uit
description: Doe het licht uit met de Ikea schakelaar voor toestellen in de huiskamer
trigger:
- device_id: 2eb5d8ea34280746cea4f1006c0bd42d
  domain: zha
  platform: device
  type: remote_button_short_press
  subtype: turn_off
condition: []
action:
  - service: light.turn_off
    target:
      entity_id:
        - light.boekenkastlinks
        - light.boekenkastrechts
        - light.marmergarage
        - light.keuken
        - light.marmerwoonkamer
  - service: switch.turn_off
    target:
      entity_id:
        - switch.garage
        - switch.garagestopcontact_schakelaar
        - switch.shelly_licht_tuin_switch_0

mode: single