alias: Licht uit zonsopgang
id: licht_uit_zonsopgang
description: Licht uit na zonsopgang
triggers:
- at: 08:00:00
  trigger: time
actions:
- target:
    entity_id: light.boekenkastlinks
  service: light.turn_off
mode: single