alias: Ventilatie tuinhuis schema
id: ventilate_garden_shed_schedule
description: Ventilate the shed for 15 minutes if temp is > 15°C or the sensor is unavailable.
trigger:
  # Trigger : Every hour
  - platform: time_pattern
    minutes: 0

condition:
  - condition: or
    conditions:
      # Condition: Temp > 15°C
      - condition: numeric_state
        entity_id: sensor.aircowoonkamer_climatecontrol_outdoor_temperature
        above: 15

      # Condition: Sensor unavailable or unknown
      - condition: state
        entity_id: sensor.aircowoonkamer_climatecontrol_outdoor_temperature
        state: 
          - "unavailable"
          - "unknown"

  # Only allow between 11:00 and 23:00 or exactly at 06:00
  - condition: or
    conditions:
      - condition: time
        after: "10:59:00"
        before: "23:01:00"
      - condition: time
        after: "05:59:00"
        before: "06:01:00"

action:
  - service: switch.turn_on
    target:
      entity_id: switch.shellyventilatorswitch

  - delay: "00:15:00"

  - service: switch.turn_off
    target:
      entity_id: switch.shellyventilatorswitch

mode: single
